In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Tiksi,RU,2020-10-20 12:51:55,71.69,128.87,12.87,93,100,18.28
1,1,Mount Gambier,AU,2020-10-20 12:51:55,-37.83,140.77,46.40,93,100,5.82
2,2,Mataura,NZ,2020-10-20 12:51:55,-46.19,168.86,46.99,81,86,1.01
3,3,Marrakesh,MA,2020-10-20 12:51:55,31.63,-8.01,95.00,16,40,19.46
4,4,Puerto Ayora,EC,2020-10-20 12:51:56,-0.74,-90.35,70.00,90,97,8.99

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [8]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
[max(temp, 0) for temp in max_temp]

[12.87,
 46.4,
 46.99,
 95.0,
 70.0,
 78.8,
 65.14,
 25.25,
 44.6,
 73.17,
 44.69,
 69.8,
 73.99,
 82.4,
 74.68,
 64.0,
 41.0,
 75.2,
 87.8,
 48.0,
 86.95,
 73.9,
 32.0,
 39.2,
 61.0,
 28.4,
 60.01,
 83.23,
 39.99,
 32.67,
 70.18,
 60.15,
 52.0,
 86.0,
 54.0,
 63.0,
 71.6,
 70.0,
 81.75,
 30.2,
 37.83,
 83.08,
 72.18,
 80.6,
 83.34,
 58.42,
 61.0,
 61.81,
 83.98,
 37.4,
 73.4,
 59.0,
 57.99,
 75.2,
 64.0,
 77.0,
 78.01,
 7.9,
 62.01,
 98.6,
 23.5,
 87.19,
 48.0,
 66.2,
 73.0,
 51.8,
 36.86,
 71.01,
 77.0,
 60.8,
 84.43,
 57.27,
 76.48,
 12.51,
 55.4,
 66.2,
 36.99,
 75.2,
 69.8,
 20.75,
 57.2,
 73.4,
 37.04,
 21.0,
 77.05,
 51.8,
 69.8,
 18.0,
 49.98,
 78.35,
 82.4,
 39.2,
 55.4,
 86.36,
 18.21,
 75.2,
 69.8,
 57.16,
 75.27,
 5.79,
 54.0,
 86.0,
 78.8,
 69.8,
 86.0,
 39.2,
 79.05,
 71.6,
 81.66,
 84.2,
 86.9,
 99.54,
 64.4,
 55.4,
 50.0,
 15.46,
 87.58,
 62.6,
 54.0,
 46.99,
 64.4,
 75.54,
 35.29,
 64.0,
 80.6,
 82.38,
 30.76,
 45.01,
 80.6,
 38.64,
 104.88,
 33.8,
 60.01,
 43.5,
 55.99,
 36.66,
 57.99,
 95.56,
 79.03,
 24.58,
 33.01,
 69.8,
 37.99,
 65.71,
 48.11,
 78.8,
 79.97,
 84.22,
 48.0,
 81.37,
 80.28,
 78.76,
 45.0,
 59.92,
 81.88,
 39.2,
 35.6,
 92.86,
 77.0,
 81.09,
 53.01,
 82.4,
 76.01,
 77.0,
 85.1,
 30.2,
 82.4,
 89.6,
 82.4,
 57.0,
 64.4,
 80.6,
 80.6,
 52.0,
 55.69,
 81.28,
 21.97,
 73.4,
 75.36,
 33.22,
 24.89,
 86.0,
 48.99,
 44.91,
 83.01,
 67.77,
 36.14,
 24.8,
 82.4,
 20.95,
 39.2,
 81.34,
 84.2,
 54.0,
 21.11,
 85.51,
 8.56,
 36.12,
 79.56,
 102.2,
 79.81,
 51.44,
 82.71,
 86.43,
 24.31,
 57.2,
 21.97,
 54.0,
 84.99,
 23.27,
 87.8,
 73.76,
 78.28,
 64.4,
 39.2,
 62.6,
 33.62,
 77.0,
 48.99,
 79.3,
 40.17,
 89.6,
 79.75,
 71.01,
 73.26,
 54.0,
 16.65,
 87.8,
 11.64,
 24.8,
 71.2,
 42.37,
 90.23,
 80.6,
 36.52,
 83.98,
 64.0,
 18.0,
 69.8,
 72.72,
 33.31,
 48.99,
 55.4,
 91.02,
 48.11,
 33.01,
 84.2,
 59.4,
 75.2,
 60.82,
 63.0,
 63.48,
 86.0,
 83.07,
 18.64,
 61.0,
 38.59,
 58.46,
 80.19,
 80.6,
 81.73,
 46.99,
 70.32,
 69.58,
 73.92,
 67.71,
 86.0,
 54.37,
 75.2,
 60.8,
 87.53,
 82.51,
 86.0,
 87.8,
 62.33,
 25.9,
 33.8,
 20.52,
 64.81,
 75.2,
 55.0,
 55.99,
 78.8,
 59.0,
 96.15,
 56.64,
 25.0,
 19.02,
 57.0,
 58.35,
 21.09,
 78.8,
 62.6,
 66.29,
 90.72,
 19.71,
 62.91,
 82.53,
 82.49,
 55.65,
 89.65,
 73.99,
 24.46,
 25.43,
 68.0,
 32.0,
 23.34,
 75.2,
 84.16,
 84.6,
 87.69,
 78.42,
 72.32,
 86.0,
 40.06,
 57.2,
 90.1,
 68.09,
 28.87,
 48.02,
 92.88,
 40.35,
 55.99,
 96.73,
 32.16,
 48.2,
 85.87,
 69.22,
 72.45,
 40.06,
 17.94,
 65.53,
 84.06,
 82.4,
 80.01,
 82.35,
 82.4,
 48.33,
 78.8,
 80.1,
 78.01,
 58.5,
 7.93,
 51.8,
 84.51,
 29.73,
 85.17,
 93.29,
 28.45,
 54.14,
 77.0,
 62.6,
 62.01,
 8.6,
 82.58,
 57.0,
 55.0,
 48.99,
 77.0,
 64.4,
 94.17,
 78.15,
 84.2,
 76.6,
 42.8,
 38.48,
 98.24,
 89.6,
 79.79,
 55.67,
 55.98,
 29.73,
 67.05,
 63.0,
 81.28,
 74.66,
 86.0,
 99.64,
 66.2,
 77.25,
 41.54,
 33.8,
 86.54,
 19.99,
 78.8,
 64.0,
 75.4,
 80.13,
 37.4,
 66.78,
 21.36,
 48.99,
 57.0,
 66.2,
 86.0,
 98.76,
 50.0,
 73.45,
 48.7,
 24.35,
 82.4,
 79.97,
 71.6,
 74.98,
 81.88,
 54.57,
 93.34,
 64.0,
 80.51,
 40.53,
 62.6,
 64.99,
 89.65,
 38.17,
 76.89,
 63.0,
 62.01,
 81.81,
 37.4,
 78.01,
 53.6,
 82.4,
 32.25,
 55.53,
 81.1,
 81.05,
 62.6,
 47.14,
 45.59,
 43.09,
 75.16,
 53.01,
 77.59,
 51.8,
 77.0,
 103.55,
 91.4,
 67.77,
 42.8,
 81.86,
 61.0,
 60.46,
 59.27,
 77.68,
 57.0,
 82.99,
 18.32,
 37.4,
 79.56,
 49.24,
 72.57,
 70.18,
 82.0,
 76.26,
 84.2,
 78.8,
 34.61,
 86.0,
 66.99,
 85.75,
 62.6,
 86.0,
 20.71,
 64.99,
 61.0,
 16.57,
 50.04,
 33.8,
 36.09,
 82.4,
 80.6,
 23.58,
 62.01,
 76.26,
 27.21,
 89.6,
 24.8,
 72.16,
 37.51,
 78.24,
 46.29,
 56.84,
 55.69,
 91.4,
 84.2,
 86.0,
 22.53,
 48.2,
 70.0,
 80.83,
 76.23,
 50.0,
 77.85,
 66.09,
 64.4,
 76.26,
 85.37,
 80.6,
 61.0,
 30.2,
 101.77,
 80.6,
 39.99,
 67.57,
 91.81,
 78.8,
 68.0,
 51.01,
 93.2,
 86.61,
 66.99,
 32.0,
 53.28,
 60.01,
 60.01,
 33.8,
 74.97,
 57.0,
 44.6,
 61.0,
 79.14,
 56.28,
 80.17,
 30.43,
 77.0,
 98.71,
 70.57,
 84.42,
 50.25,
 66.79,
 75.27,
 40.41,
 59.0,
 70.52,
 73.99,
 42.8,
 63.0,
 91.99,
 62.01,
 80.6,
 75.2,
 69.01,
 71.62,
 86.36,
 42.8,
 73.99,
 56.71,
 91.11,
 92.25,
 81.95,
 60.8,
 57.99,
 56.79,
 82.49,
 36.0,
 64.4,
 57.99,
 45.34,
 75.97,
 96.8,
 72.0,
 28.2,
 64.99,
 33.76,
 83.07,
 69.8,
 41.0,
 53.01,
 80.6,
 86.77,
 13.91,
 60.8,
 41.0,
 80.6,
 87.8,
 44.6,
 61.0,
 82.4,
 72.72,
 41.5,
 55.15,
 36.0,
 80.91,
 75.2,
 62.6,
 86.31,
 39.2,
 57.0,
 78.8,
 63.55,
 32.34,
 40.19,
 50.0,
 83.46,
 31.8]

In [11]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [22]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [23]:
# Heatmap of percent wind Speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [25]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [31]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)].dropna()
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
5,5,Saint-Joseph,RE,2020-10-20 12:51:56,-21.37,55.62,78.80,69,36,21.92
13,13,Damietta,EG,2020-10-20 12:51:57,31.42,31.81,82.40,69,0,9.17
17,17,Las Choapas,MX,2020-10-20 12:51:58,17.93,-94.08,75.20,88,20,3.56
18,18,Salalah,OM,2020-10-20 12:47:28,17.02,54.09,87.80,52,23,8.05
20,20,Tiznit,MA,2020-10-20 12:51:58,29.58,-9.50,86.95,15,70,19.46
27,27,Hithadhoo,MV,2020-10-20 12:51:59,-0.60,73.08,83.23,77,55,12.21
33,33,Gat,IL,2020-10-20 12:52:00,31.61,34.76,86.00,53,0,5.99
38,38,Tamandare,BR,2020-10-20 12:52:02,-8.76,-35.10,81.75,59,41,10.45
41,41,Kavieng,PG,2020-10-20 12:52:02,-2.57,150.80,83.08,72,85,7.09
43,43,Wahiawa,US,2020-10-20 12:48:11,21.50,-158.02,80.60,100,90,3.33

In [34]:
preferred_cities_df.count()

City_ID       192
City          192
Country       192
Date          192
Lat           192
Lng           192
Max Temp      192
Humidity      192
Cloudiness    192
Wind Speed    192
dtype: int64

In [35]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

            City Country  Max Temp    Lat     Lng Hotel Name
5   Saint-Joseph      RE     78.80 -21.37   55.62
13      Damietta      EG     82.40  31.42   31.81
17   Las Choapas      MX     75.20  17.93  -94.08
18       Salalah      OM     87.80  17.02   54.09
20        Tiznit      MA     86.95  29.58   -9.50
27     Hithadhoo      MV     83.23  -0.60   73.08
33           Gat      IL     86.00  31.61   34.76
38     Tamandare      BR     81.75  -8.76  -35.10
41       Kavieng      PG     83.08  -2.57  150.80
43       Wahiawa      US     80.60  21.50 -158.02

In [37]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [42]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
   # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [43]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
5,Saint-Joseph,RE,78.80,-21.37,55.62,"""Plantation Bed and Breakfast"
13,Damietta,EG,82.40,31.42,31.81,العواد لتجارة الابلكاش
17,Las Choapas,MX,75.20,17.93,-94.08,Hotel Jysmak
18,Salalah,OM,87.80,17.02,54.09,HAMDAN PLAZA HOTEL
20,Tiznit,MA,86.95,29.58,-9.50,
27,Hithadhoo,MV,83.23,-0.60,73.08,Scoop Guest House
33,Gat,IL,86.00,31.61,34.76,OlusHome
38,Tamandare,BR,81.75,-8.76,-35.10,Pousada 100 Passos
41,Kavieng,PG,83.08,-2.57,150.80,Nusa Island Retreat
43,Wahiawa,US,80.60,21.50,-158.02,Aloha Wahiawa

In [45]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [46]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [47]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))